jobs:
  include:
    - stage: build_docs
      language: node_js
      node_js:
        - "12"
      before_script:
      - npm install -g @redocly/openapi-cli && npm install -g redoc-cli
      - npm install -g gh-openapi-docs
      script:
      - gh-openapi-docs
      deploy:
        provider: pages
        skip-cleanup: true
        keep_history: true
        github-token: $GITHUB_TOKEN
        on:
          all_branches: true